openapi: 3.0.0
info:
  title: Category
  description: Product Category
  version: 1.0.0
components:
  responses:
    GetCategoryByIdResponse:
      description: get category by id response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Category'

  parameters:
    CategoryIdParameter:
      name: categoryId
      in: path
      required: true
      description: category id
      schema:
        type: string

  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string


servers:
  - url: 'https://{hostname}/api'
paths:
  /category/{categoryId}:
    get:
      parameters:
        - $ref: '#/components/parameters/CategoryIdParameter'
      description: get category by id
      responses:
        '200':
          $ref: '#/components/responses/GetCategoryByIdResponse'
  /category:
    post:
      operationId: createCategory
      description: create new category
      requestBody:
        content:
          application/json:
           schema:
             $ref: "#/components/schemas/Category"
      responses:
        '201':
          description: OK

